package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(bb534eb52c0dabe140281e4d557e2b3c)
 */
public class Application  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String apply;

    public Application() {
    }

    public Application(java.lang.String apply) {
        this.apply = apply;
    }


    
    public java.lang.String getApply() {
        return this.apply;
    }

    public void setApply(java.lang.String apply) {
        this.apply = apply;
    }
}