package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(5fe0804eb2a520624a7e94cf741a41d0)
 */
public class SSNCardApplication extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String ssn;

    public SSNCardApplication() {
    }

    public SSNCardApplication(java.lang.String ssn, java.lang.String address, java.lang.Integer age) {
        this.ssn = ssn;
        this.address = address;
        this.age = age;
    }


    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public java.lang.String getSsn() {
        return this.ssn;
    }

    public void setSsn(java.lang.String ssn) {
        this.ssn = ssn;
    }
}