package org.kie.example.project1;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(4c4f2638ca697f6f06c572a6e031d5c9)
 */
public class SSNCardApplication  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String ssn;

    public SSNCardApplication() {
    }

    public SSNCardApplication(java.lang.String ssn, java.lang.String address) {
        this.ssn = ssn;
        this.address = address;
    }


    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getSsn() {
        return this.ssn;
    }

    public void setSsn(java.lang.String ssn) {
        this.ssn = ssn;
    }
}